# Generated by Django 5.2.5 on 2025-08-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Isbn', models.CharField(unique=True)),
                ('Published_date', models.DateField(max_length=255)),
                ('Genre', models.CharField(max_length=255)),
                ('Date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
